### ISSUE TITLE
Use Official Email Address For CTA

### ISSUE THREAD

**Issue by nicolaspearson** [nicolaspearson/react.studio.repro#2]
Add official email address to click events on CTA buttons.

**Comment by nicolaspearson** [comment]
@brndnmg please provide an email address where clients will be able to get in touch with someone at Studio Repro.

**Comment by brndnmg** [comment]
Awaiting confirmation, domain is **studiorepro.co**

**Comment by brndnmg** [comment]
**info@studiorepro.co**

**Comment by nicolaspearson** [comment]
@brndnmg, you are a scholar and a gent!

**Comment by brndnmg** [comment]
https://dbqu26fva8gd1.cloudfront.net
